In [3]:
# %load ~/dotfiles/root/usr/local/share/pythonstartup.py
import cmath
import functools
import itertools
import math
import os
import sys

from cmath import phase, polar
from functools import namedtuple, partial
from pprint import pprint
from time import time, sleep
from timeit import timeit

import cv2
import matplotlib.pyplot as plt
import numpy as np

from numpy import array, arange, concatenate, ones, ones_like, zeros, zeros_like
from numpy import exp, log, log2, log10, sqrt, ceil, floor
from numpy import pi, sin, cos, tan, arcsin, arccos, arctan, arctan2, degrees, radians
from scipy import optimize, signal
from scipy.constants import *

j = 1.j

np.set_printoptions(precision=3)

def E(x, precision=3):
    return ('{:.' + str(precision) + 'E}').format(x)

def print(*args):
    def reformat(x):
        return (
            "{:.3f}".format(x) if isinstance(x, float)   else
            "{:.3f}".format(x) if isinstance(x, complex) else
            x)
    __builtins__.print(*map(reformat, args))

def namestr(obj, namespace):
    return next(name for name in namespace if namespace[name] is obj)

def printn(*args, namespace=globals(), padding=20):
    for x in args:
        print(namestr(x, namespace).ljust(padding), x)


In [13]:
# Q1

# Find inverse mod 17 of following:
items = [2, 3, 5, 11]
m = 17

def p_mod_inv(x, m):
    return x**(m-2) % m

inverses = [p_mod_inv(x, m) for x in items]
verify   = [p_mod_inv(x, m) * x % m for x in items]

printn(items, inverses, verify)

items                [2, 3, 5, 11]
inverses             [9, 6, 7, 14]
verify               [1, 1, 1, 1]


In [69]:
# Q2

# ax + by ≡ c (mod 11)
sys_a = np.array([
    [2, 3, 5],
    [1, 5, 6]])

sys_b = np.array([
    [4, 1, 5],
    [1, 3, 4]])

def is_solution(arr, x, y):
    return not np.any(arr.dot(np.array([x, y, -1])) % 11)

sys_a_sol = [(x, y) for x, y in itertools.product(range(3*11), range(11*11)) if is_solution(sys_a, x, y)]
sys_b_sol = [(x, y) for x, y in itertools.product(range(1*11), range(11*11)) if is_solution(sys_b, x, y)]

sys_a_sol = np.array(sys_a_sol).reshape(-1, 11, 2)
sys_b_sol = np.array(sys_b_sol).reshape(-1, 11, 2)

#printn(sys_a_sol, sys_b_sol)
printn(sys_b_sol)

sys_b_sol            [[[  0   5]
  [  0  16]
  [  0  27]
  [  0  38]
  [  0  49]
  [  0  60]
  [  0  71]
  [  0  82]
  [  0  93]
  [  0 104]
  [  0 115]]

 [[  1   1]
  [  1  12]
  [  1  23]
  [  1  34]
  [  1  45]
  [  1  56]
  [  1  67]
  [  1  78]
  [  1  89]
  [  1 100]
  [  1 111]]

 [[  2   8]
  [  2  19]
  [  2  30]
  [  2  41]
  [  2  52]
  [  2  63]
  [  2  74]
  [  2  85]
  [  2  96]
  [  2 107]
  [  2 118]]

 [[  3   4]
  [  3  15]
  [  3  26]
  [  3  37]
  [  3  48]
  [  3  59]
  [  3  70]
  [  3  81]
  [  3  92]
  [  3 103]
  [  3 114]]

 [[  4   0]
  [  4  11]
  [  4  22]
  [  4  33]
  [  4  44]
  [  4  55]
  [  4  66]
  [  4  77]
  [  4  88]
  [  4  99]
  [  4 110]]

 [[  5   7]
  [  5  18]
  [  5  29]
  [  5  40]
  [  5  51]
  [  5  62]
  [  5  73]
  [  5  84]
  [  5  95]
  [  5 106]
  [  5 117]]

 [[  6   3]
  [  6  14]
  [  6  25]
  [  6  36]
  [  6  47]
  [  6  58]
  [  6  69]
  [  6  80]
  [  6  91]
  [  6 102]
  [  6 113]]

 [[  7  10]
  [  7  21]
  [  7  32]
  [  